// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {stripe} from '../models';
import {main} from '../models';

export function CreateCustomer(arg1:string,arg2:string,arg3:boolean):Promise<stripe.StripeCustomerView>;

export function CreateInvoice(arg1:string,arg2:string,arg3:number,arg4:string):Promise<string>;

export function ForceRefreshCache():Promise<void>;

export function GetCoupons():Promise<{[key: string]: stripe.StripeCoupon}>;

export function GetCustomers():Promise<Array<stripe.StripeCustomerView>>;

export function GetProducts():Promise<Array<stripe.StripeProductView>>;

export function GetSettings():Promise<main.Settings>;

export function SetAPIKey(arg1:string):Promise<void>;
