// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCustomer(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateCustomer'](arg1, arg2, arg3);
}

export function CreateInvoice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateInvoice'](arg1, arg2, arg3, arg4);
}

export function ForceRefreshCache() {
  return window['go']['main']['App']['ForceRefreshCache']();
}

export function GetCoupons() {
  return window['go']['main']['App']['GetCoupons']();
}

export function GetCustomers() {
  return window['go']['main']['App']['GetCustomers']();
}

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}
